language: python
python:
    - "2.7.12"
# Install all dependencies
install:
    - pip install -r requirements.txt

services:
    - postgresql
# command to create database
before_script:
    - psql -c 'create database sample_db;' -U postgres
# command to run tests
script:
    - pytest --cov=./recipe/
after_success:
    - coveralls