language: python
python:
    - "3.6.3"
# Install all dependencies
install:
    - pip install -r requirements.txt
    - pip install coveralls

services:
    - postgresql
# command to create database
before_script:
    - psql -c 'create database main_db;' -U postgres
# command to run tests
script:
    - py.test
after_success:
    - coveralls